import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { api } from "y/utils/api";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  const { data } = api.assets.getAll.useQuery();
  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b">
        {!user.isSignedIn && <SignInButton />}
        {!!user.isSignedIn && <SignOutButton />}
        {/* <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" /> */}
        {/* <div>
          {data?.map((asset) => (
            <div key={asset.id}>
              <Link href={`/assets/${asset.id}`}>
                <a>{asset.deedNo}</a>
              </Link>
            </div>
          ))}
        </div> */}
      </main>
    </>
  );
}
